export { Home } from './Home';
export { Dashboard } from './Dashboard';
export { Estoque } from './Estoque';
export { Produtos } from './Produtos';
export { ProdutosAdmin } from './Admin/Produtos';
export { Pedidos } from './Pedidos';
export { Comentarios } from './Comentarios';
export { Configuracoes } from './Configuracoes';
export { Login } from './Login';
